---
title: "ARIMA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xts)
library(forecast)
library(tseries)
```
  
```{r}

r <- function(df){
  # load the data
  df1 <- read.csv(df)[,c('Date','Adj.Close')] %>% mutate(Date = as_date(Date))
  # convert to time series 
  df2 <- xts(df1[,-1], order.by = as.Date(df1[,1]), '%m/%d%Y')
  # Compute the log returns for the stock
  r <- diff(log(df2), lag = 1)
  # drop NAs
  r <- r[!is.na(r)]
  return(r)
}

stock <- function(df){
  df1 <- read.csv(df)[,c('Date','Adj.Close')] %>% mutate(Date = as_date(Date))
  stock <- xts(df1[,-1], order.by = as.Date(df1[,1]), '%m/%d%Y')
  return(stock)
}

```

```{r}
# load the returns
SnP500_r <- r('./Data/SnP500.csv')
SnP500 <- stock('./Data/SnP500.csv') 
# plot the series 
plot(SnP500)
# Conduct ADF test on log returns series
print(adf.test(SnP500_r))

z <- decompose(SnP500, type="additive")
plot(z)

```

```{r}

# Apply the ACF and PACF functions
par(mfrow = c(2,2))
acf_r <- acf(SnP500, main='ACF Plot', lag.max=100)
pacf_r <- pacf(SnP500, main='PACF Plot', lag.max=100)
TSA::eacf(SnP500)
# ARIMA(1,0,0)

```

```{r}

# Split the dataset in two parts - training and testing
breakpoint <- floor(nrow(SnP500_r)*(4/5))
par(mfrow = c(2,2))
acf_r <- acf(SnP500[1:breakpoint], main='ACF Plot', lag.max=100)
pacf_r <- pacf(SnP500[1:breakpoint], main='PACF Plot', lag.max=100)

fit <- arima(SnP500[1:breakpoint], order = c(1,0,0), include.mean = T)
acf(fit$residuals)
pacf(fit$residuals)
# no obvious auto-correlations among residuals

arima.forecast <- forecast(fit, h = 1, level=95)
summary(arima.forecast)

```

```{r}

# SnP500[breakpoint+1]

# Initialzing an xts object for Actual log returns
Actual_series <- xts(0, as.Date("2017-12-27","%Y-%m-%d"))
# Initialzing a dataframe for the forecasted return series
forecasted_series <- data.frame(Forecasted = numeric())
n <- nrow(SnP500)

for (b in breakpoint:(n-1)){
  
  # form the training dataset and the test dataset based on the dynamic breakpoint.
  train <- SnP500[1:b]
  test <- SnP500[(b+1):n]
 
   # Summary of the ARIMA model using the determined (p,d,q) parameters
  fit <- arima(train, order = c(1,0,0), include.mean = T)
  
  # Forecasting the log returns, 95% prediction interval 
  arima.forecast <- forecast(fit, h = 1, level=95)

  # Creating a series of forecasted returns for the forecasted period
  forecasted_series <- rbind(forecasted_series,arima.forecast$mean[1])
  colnames(forecasted_series) = c("Forecasted")
  
  # Creating a series of actual returns for the forecasted period
  Actual_return <- SnP500[b+1]
  Actual_series <- c(Actual_series,xts(Actual_return))
  rm(Actual_return)
}



```

```{r}
# Plotting a acf plot of the residuals
acf(fit$residuals, main = 'Residual plots')
summary(arima.forecast)
```

```{r}
# comparing the forecasted returns versus the actual returns.

# Adjust the length of the Actual return series
Actual <- Actual_series[-1]
# Create a time series object of the forecasted series
Forecasted <- xts(forecasted_series,index(Actual))

# Create a plot of the two return series - Actual versus Forecasted
plot(Actual,type='l',main='Actual Returns Vs Forecasted Returns')
lines(Forecasted,lwd=1.5,col='red')
legend('bottomright',c("Actual","Forecasted"),lty=c(1,1),lwd=c(1.5,1.5),col=c('black','red'))

# Create a table for the accuracy of the forecast
comparsion <- merge(Actual,Forecasted)
comparsion$Accuracy <- sign(comparsion$Actual) == sign(comparsion$Forecasted)
print(comparsion)

# Compute the accuracy percentage metric
Accuracy_percentage <- sum(comparsion$Accuracy == 1)*100/length(comparsion$Accuracy)
print(Accuracy_percentage)

```









